### ISSUE TITLE
Issue-hello solana

### ISSUE THREAD

**Issue by drone-1x** [drone-1x/pro-sol#34]
Automated Review Comments
Issues in program-basics/hello-solana/README.md:
  - (6, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
Issues in program-basics/hello-solana/anchor/Anchor.toml:
  - (11, 'Hardcoded string found')
Issues in program-basics/hello-solana/anchor/Cargo.toml:
  - (9, 'Hardcoded string found')
Issues in program-basics/hello-solana/anchor/package.json:
  - (3, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
Issues in program-basics/hello-solana/anchor/programs/create-system-account/Cargo.toml:
  - (5, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in program-basics/hello-solana/anchor/tests/anchor.ts:
  - (6, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in program-basics/hello-solana/anchor/tsconfig.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in program-basics/hello-solana/native/cicd.sh:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
Issues in program-basics/hello-solana/native/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in program-basics/hello-solana/native/program/Cargo.toml:
  - (3, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in program-basics/hello-solana/native/test.ts:
  - (13, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
Issues in program-basics/hello-solana/native/tsconfig.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')

**Comment by angel-1x** [comment]
I got it.
